creation_rules:
    - age: >-
        age1tc9aar0hzactnnm5p38hzq3vhkjwxu95fnqawkdvzdkqpcr7lqwsg0m54r,
        age19q2ds685y4cmjc00rsnzz446vvyjdwsm538xuw9legt5uv7dh5fsvwqu7a,
        age1g57ymcq7lj6xjaulsehs68f9560cuwfvgmp93rzm3q6ukg2rvpesuyutxj,
        age1whpakrnu294ug322ta5as8f4gllq6szxj7zqe4xkaeqk8lttyucskatqcc
